{
 "title": "Memory & Temp",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "temp_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "disk_free", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "mem_available", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 12 },
   "targets": [
    { "expr": "cpu_usage_idle", "legendFormat": "__auto" }
   ]
  }
 ]
}