{
 "title": "Switches : Interface Rate (P)",
 "description": "Switches  : Interface Rate (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Sampling", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "switch",
    "label": "switch",
    "query": {
     "query": "label_values(interfaces_counters_in_unicast_pkts,source)"
    }
   },
   {
    "name": "netif",
    "label": "Network Interface",
    "query": {
     "query": "label_values(interfaces_counters_in_unicast_pkts{source=\"$switch\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "netif",
   "targets": [
    {}
   ]
  },
  {
   "title": "Link Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interfaces_ifindex{source=~\"[[switch]]\",name=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "Link MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interfaces_mtu{source=~\"[[switch]]\",name=~\"[[netif]]\"}"
    }
   ]
  },
  {
   "title": "$netif : Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ifcounters_in_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}",
     "legendFormat": "IN (bps)"
    },
    {
     "expr": "rate(ifcounters_out_bits_per_second{host=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (bps)"
    }
   ]
  },
  {
   "title": "$netif : Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "interfaces_counters_in_unicast_pkts{source=~\"[[switch]]\",name=~\"[[netif]]\"}",
     "legendFormat": "IN (pps)"
    },
    {
     "expr": "rate(interfaces_counters_out_unicast_pkts{source=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (pps)"
    }
   ]
  },
  {
   "title": "$netif : Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "interfaces_counters_in_discards{source=~\"[[switch]]\",name=~\"[[netif]]\"}",
     "legendFormat": "IN (discards)"
    },
    {
     "expr": "rate(interfaces_counters_out_discards{source=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (discards)"
    },
    {
     "expr": "rate(interfaces_counters_in_errors{source=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "IN (errors)"
    },
    {
     "expr": "rate(interfaces_counters_out_errors{source=~\"[[switch]]\",name=~\"[[netif]]\"}[20s])",
     "legendFormat": "OUT (errors)"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((interfaces_ifindex{source=~\"[[switch]]\",name=~\"[[netif]]\"})*8)/1000000000"
    }
   ]
  }
 ]
}