---
version: 2
updates:
# actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
# integration
  - package-ecosystem: "docker"
    directory: "/integration/gateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/host-cpu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/otel"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/xpu-cpu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/pxe"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/spdk"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/integration/strongswan"
    schedule:
      interval: "weekly"
# storage
  - package-ecosystem: "gomod"
    directory: "/storage/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/storage/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/storage/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/storage/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/storage/spdk"
    schedule:
      interval: "weekly"
# security
  - package-ecosystem: "gomod"
    directory: "/security/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/security/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/security/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/security/client"
    schedule:
      interval: "weekly"