version: '3.7'

services:

  traffic_controller:
    image: ${DOCKER_REGISTRY}/ixia-c-controller:${CONTROLLER_VERSION:-latest}
    container_name: ixia-c-controller-${USER}
    command: --accept-eula
    network_mode: "host"
    restart: always

  traffic_engine_1:
    image: ${DOCKER_REGISTRY}/ixia-c-traffic-engine:${TRAFFIC_ENGINE_VERSION:-latest}
    container_name: ixia-c-traffic-engine1-${USER}
    network_mode: "service:vpn-client"
    depends_on:
    - vpn-client
    restart: always
    privileged: true
    cpuset: ${CPU_CORES_IFC1:-"0"}
    environment:
    - OPT_LISTEN_PORT=${TCP_PORT_IFC1:-5555}
    - ARG_IFACE_LIST=virtual@af_packet,${IFC1}
    - OPT_NO_HUGEPAGES=Yes
    - OPT_ENABLE_IPv6=${OPT_ENABLE_IPv6}

  traffic_engine_2:
    image: ${DOCKER_REGISTRY}/ixia-c-traffic-engine:${TRAFFIC_ENGINE_VERSION:-latest}
    container_name: ixia-c-traffic-engine2-${USER}
    network_mode: "host"
    restart: always
    privileged: true
    cpuset: ${CPU_CORES_IFC2:-"1"}
    environment:
    - OPT_LISTEN_PORT=${TCP_PORT_IFC2:-5556}
    - ARG_IFACE_LIST=virtual@af_packet,${IFC2}
    - OPT_NO_HUGEPAGES=Yes
    - OPT_ENABLE_IPv6=${OPT_ENABLE_IPv6}

  vpn-client:
    image: strongx509/strongswan:5.9.9
    container_name: vpn-client-${USER}
    network_mode: "host"
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
    - ./conf/client/k.swanctl.conf:/etc/swanctl/conf.d/k.swanctl.conf
    - ./conf/client/vici.conf:/etc/strongswan.d/charon/vici.conf
    #- ./conf/strongswan-client.conf:/etc/strongswan.conf
    command:
    - './charon'
