version: "3.7"

services:

  spdk:
    image: "ghcr.io/opiproject/opi-spdk:${SPDK_TAG-main}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev/hugepages:/dev/hugepages
      - /dev/shm:/dev/shm
      - /proc:/proc
      - /var/tmp
    ports:
      - "9009:9009"
    privileged: true
    networks:
      - opi
    working_dir: /usr/libexec/spdk/scripts
    command: |
      sh -x -c 'sync; echo 1 > /proc/sys/vm/drop_caches  && \
            echo 1024 > /proc/sys/vm/nr_hugepages && \
            grep "" /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages && \
            /usr/local/bin/spdk_tgt -m 0x1 -s 512 --no-pci 2>&1 & \
            for i in `seq 1 10`; do ./rpc.py spdk_get_version && break || sleep 1; done  && \
            ./rpc.py bdev_malloc_create -b Malloc0 64 512 && \
            ./rpc.py bdev_malloc_create -b Malloc1 64 512 && \
            ./rpc_http_proxy.py 0.0.0.0 9009 spdkuser spdkpass'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  opi-spdk-server:
    image: golang:alpine
    working_dir: /app
    volumes_from:
      - spdk:rw
    volumes:
      - ./:/app
    ports:
      - '50051:50051'
    networks:
      - opi
    command: go run jsonrpc.go server.go

  opi-spdk-client:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - opi
    command: go run client.go -addr=opi-spdk-server:50051
    depends_on:
      - opi-spdk-server

networks:
  opi:

