version: '3.7'

services:

  xpu-cpu-ssh:
    image: linuxserver/openssh-server:amd64-latest
    hostname: xpu-cpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=xpu
    ports:
      - '2207:2222'
    networks:
      opi:
        ipv4_address: 10.127.127.7

  xpu-cpu:
    build:
      context: xpu-cpu
    depends_on:
      - xpu-cpu-ssh
    network_mode: service:xpu-cpu-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']

  xpu-telegraf:
    image: telegraf:1.22
    volumes:
      - ./xpu-cpu/telegraf-redfish.conf:/etc/telegraf/telegraf.conf:ro
    network_mode: service:xpu-cpu-ssh

  xpu-bmc-ssh:
    image: linuxserver/openssh-server:amd64-latest
    hostname: xpu-bmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=bmc
    ports:
      - '2209:2222'
      - '8002:8000'
    networks:
      opi:
        ipv4_address: 10.127.127.9

  xpu-bmc-redfish:
    image: dmtf/redfish-mockup-server:1.1.8
    network_mode: service:xpu-bmc-ssh

  xpu-bmc:
    build:
      context: xpu-bmc
    network_mode: service:xpu-bmc-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']

networks:
  opi:
    external: true
