version: '3.7'

services:

  xpu-cpu-ssh:
    image: linuxserver/openssh-server:amd64-latest
    hostname: xpu-cpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=xpu
    ports:
      - '2207:2222'
      - "9009:9009"
    networks:
      opi:
        ipv4_address: 10.127.127.7
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-cpu:
    build:
      context: xpu-cpu
    depends_on:
      - xpu-cpu-ssh
    volumes_from:
      - xpu-cpu-ssh:rw
    network_mode: service:xpu-cpu-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']
    healthcheck:
      test: cat /proc/1/status || exit 1
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-telegraf:
    image: telegraf:1.22
    volumes:
      - ./xpu-cpu/telegraf-redfish.conf:/etc/telegraf/telegraf.conf:ro
    network_mode: service:xpu-cpu-ssh

  xpu-spdk:
    build:
      context: spdk
    volumes:
      - /dev/hugepages:/dev/hugepages
      - /dev/shm:/dev/shm
      - /proc:/proc
    privileged: true
    network_mode: service:xpu-cpu-ssh
    command: |
      sh -c 'echo 512 > /proc/sys/vm/nr_hugepages && \
            grep "" /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages && \
            /root/spdk/build/bin/spdk_tgt -m 0x1 -s 512 2>&1 \
            echo wait 5s... && sleep 5s && cd /root/spdk/scripts && \
            ./rpc.py bdev_nvme_attach_controller -b opi-bdev -t tcp -a spdk-target -f ipv4 -s 4420 -n nqn.2016-06.io.spdk:cnode1 && \
            ./rpc_http_proxy.py 0.0.0.0 9009 spdkuser spdkpass'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-bmc-ssh:
    image: linuxserver/openssh-server:amd64-latest
    hostname: xpu-bmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=bmc
    ports:
      - '2209:2222'
      - '8002:8000'
    networks:
      opi:
        ipv4_address: 10.127.127.9
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-bmc-redfish:
    image: dmtf/redfish-mockup-server:1.1.8
    network_mode: service:xpu-bmc-ssh

  xpu-bmc:
    build:
      context: xpu-bmc
    volumes_from:
      - xpu-bmc-ssh:rw
    network_mode: service:xpu-bmc-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']
    healthcheck:
      test: cat /proc/1/status || exit 1
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  opi:
    external: true
