---
version: '3.7'

services:

  dhcp:
    image: ghcr.io/opiproject/opi-dhcp-server:main@sha256:19e4212369b5054abd27befe143b2a73be2a4f3f6a0cf98272438946bc5ccc98
    environment:
      NODE_IP_SUBNET: 10.127.127.0
      NODE_IP_NETMASK: 255.255.255.0
      NODE_IP_RANGE_MIN: 10.127.127.100
      NODE_IP_RANGE_MAX: 10.127.127.253
      NODE_IP_ADDRESS: 10.127.127.3
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.3
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: sh -e -u -x -c 'envsubst < /etc/dhcp/dhcpd.conf.template > /etc/dhcp/dhcpd.conf && dhcpd -d'

  nmap:
    image: docker.io/instrumentisto/nmap:7.93
    networks:
      - xpu-cpu
    command: --script broadcast-dhcp-discover

  web:
    image: ghcr.io/opiproject/opi-web:main@sha256:0ea893d4b4e0dc9f735c36a489ec9a4b16390e8bff93819686754eea0961df5c
    ports:
      - 8082:8082
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.16
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: python3 -m http.server 8082

  bootstrap:
    image: ghcr.io/opiproject/opi-sztp-server:main@sha256:5f41798437260530519d553df7487ca6f0bf43490eb44cb3d8bc468f9ea71af7
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_SBI_PORT: 9090
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
      SZTPD_OPI_MODE: "running"
      SZTPD_RETRY_ATTEMPTS: 30
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.11
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]

  redirecter:
    image: ghcr.io/opiproject/opi-sztp-server:main@sha256:5f41798437260530519d553df7487ca6f0bf43490eb44cb3d8bc468f9ea71af7
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_SBI_PORT: 8080
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
      BOOTSVR_PORT: 9090
      BOOTSVR_ADDR: "bootstrap"
      SZTPD_OPI_MODE: "redirect"
      SZTPD_RETRY_ATTEMPTS: 30
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.12
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]

  dhclient:
    image: ghcr.io/opiproject/opi-dhcp-client:main@sha256:12109507f4c9accce2df97bec00de621d490f0926152f665d4260da9fee94481
    cap_add:
      - CAP_NET_RAW
    volumes:
      - dhcp-leases-folder:/var/lib/dhclient/
    network_mode: service:web
    command: dhclient -d -v

  agent:
    image: ghcr.io/opiproject/opi-sztp-agent:main@sha256:40c99ecc67805365cd9622ce0b3b8179a5cbfaa331a79dd8d3a3ed348116b139
    depends_on:
      bootstrap:
        condition: service_healthy
      redirecter:
        condition: service_healthy
    volumes_from:
      - dhclient:ro
    networks:
      - xpu-cpu
    command: ['/opi-sztp-agent', 'daemon']

volumes:
  dhcp-leases-folder:

networks:
  xpu-cpu:
    external: true
