version: '3.7'

services:

  pxe:
    build:
      context: pxe
    environment:
      NODE_IP_SUBNET: 10.127.127.0
      NODE_IP_NETMASK: 255.255.255.0
      NODE_IP_RANGE_MIN: 10.127.127.100
      NODE_IP_RANGE_MAX: 10.127.127.253
      NODE_IP_ADDRESS: 10.127.127.3
    volumes:
      - ./pxe/dhcpd.conf.template:/etc/dhcp/dhcpd.conf.template:z,ro
      - ./pxe/grubx64.efi:/var/lib/tftpboot/grubx64.efi:z,ro
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.3
    healthcheck:
      test: tftp localhost -v -c get grubx64.efi || exit 1
      interval: 6s
      timeout: 10s
      retries: 5
    command: |
      sh -e -u -x -c 'envsubst < /etc/dhcp/dhcpd.conf.template > /etc/dhcp/dhcpd.conf && \
            /usr/sbin/in.tftpd --listen -s /var/lib/tftpboot  && \
            dhcpd -d & \
            wait'
  web:
    image: python:3.9
    ports:
      - 8082:8082
    volumes:
      - ./pxe/grubx64.efi:/var/lib/tftpboot/grubx64.efi:z,ro
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.16
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
      interval: 6s
      timeout: 10s
      retries: 5
    command: python3 -m http.server 8082

  sztp:
    build:
      context: pxe
      dockerfile: Dockerfile.sztp
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.11
    command: ['sztpd', 'sqlite:///:memory:']
    healthcheck:
      test: curl --silent --fail -H Accept:application/yang-data+json http://localhost:1080/.well-known/host-meta || exit 1
      interval: 6s
      timeout: 10s
      retries: 5

networks:
  xpu-cpu:
    external: true
