version: '3.7'

services:

  pxe:
    build:
      context: pxe
    ports:
      - 8082:8082
    environment:
      NODE_IP_SUBNET: 10.10.255.8
      NODE_IP_NETMASK: 255.255.255.248
      NODE_IP_RANGE_MIN: 10.10.255.9
      NODE_IP_RANGE_MAX: 10.10.255.14
      NODE_IP_ADDRESS: 10.10.255.9
    volumes:
      - ./pxe/grubx64.efi:/var/lib/tftpboot/grubx64.efi:ro
      - ./pxe/dhcpd.conf.template:/etc/dhcp/dhcpd.conf.template:ro
    networks:
      - opi
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
      interval: 6s
      timeout: 10s
      retries: 5
    command: |
      sh -e -u -x -c 'envsubst < /etc/dhcp/dhcpd.conf.template > /etc/dhcp/dhcpd.conf && \
            /usr/sbin/in.tftpd --listen -s /var/lib/tftpboot  && \
            python3 -m http.server 8082 & \
            dhcpd -d & \
            /root/spdk/build/bin/spdk_tgt -m 0xff -s 1024 > /tmp/spdk-tgt.log 2>&1 & \
            wait'
networks:
  opi:
