version: "3.7"

services:

  telegraf-on-dpu:
    image: telegraf:1.22
    volumes:
      - ./telegraf/telegraf-redfish.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - opi
    healthcheck:
      test: cat /proc/1/status || exit 1
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  otel-gw-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      - opi

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.36.2
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - opi

networks:
  opi:
    name: opi
    external: true
