// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/storage/storage.proto

package opiapistorage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FrontEnd struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Nvme                 []*FrontEnd_NVMe       `protobuf:"bytes,3,rep,name=nvme,proto3" json:"nvme,omitempty"`
	Virtioscsi           []*FrontEnd_VirtioScsi `protobuf:"bytes,4,rep,name=virtioscsi,proto3" json:"virtioscsi,omitempty"`
	Virtiofs             []*FrontEnd_VirtioFS   `protobuf:"bytes,5,rep,name=virtiofs,proto3" json:"virtiofs,omitempty"`
	Virtioblk            []*FrontEnd_VirtioBlk  `protobuf:"bytes,6,rep,name=virtioblk,proto3" json:"virtioblk,omitempty"`
	LastUpdated          *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FrontEnd) Reset()         { *m = FrontEnd{} }
func (m *FrontEnd) String() string { return proto.CompactTextString(m) }
func (*FrontEnd) ProtoMessage()    {}
func (*FrontEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0}
}

func (m *FrontEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd.Unmarshal(m, b)
}
func (m *FrontEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd.Marshal(b, m, deterministic)
}
func (m *FrontEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd.Merge(m, src)
}
func (m *FrontEnd) XXX_Size() int {
	return xxx_messageInfo_FrontEnd.Size(m)
}
func (m *FrontEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd proto.InternalMessageInfo

func (m *FrontEnd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd) GetNvme() []*FrontEnd_NVMe {
	if m != nil {
		return m.Nvme
	}
	return nil
}

func (m *FrontEnd) GetVirtioscsi() []*FrontEnd_VirtioScsi {
	if m != nil {
		return m.Virtioscsi
	}
	return nil
}

func (m *FrontEnd) GetVirtiofs() []*FrontEnd_VirtioFS {
	if m != nil {
		return m.Virtiofs
	}
	return nil
}

func (m *FrontEnd) GetVirtioblk() []*FrontEnd_VirtioBlk {
	if m != nil {
		return m.Virtioblk
	}
	return nil
}

func (m *FrontEnd) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_NVMe struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontEnd_NVMe) Reset()         { *m = FrontEnd_NVMe{} }
func (m *FrontEnd_NVMe) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_NVMe) ProtoMessage()    {}
func (*FrontEnd_NVMe) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 0}
}

func (m *FrontEnd_NVMe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_NVMe.Unmarshal(m, b)
}
func (m *FrontEnd_NVMe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_NVMe.Marshal(b, m, deterministic)
}
func (m *FrontEnd_NVMe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_NVMe.Merge(m, src)
}
func (m *FrontEnd_NVMe) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_NVMe.Size(m)
}
func (m *FrontEnd_NVMe) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_NVMe.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_NVMe proto.InternalMessageInfo

func (m *FrontEnd_NVMe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_NVMe) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FrontEnd_NVMe_NVMeSubsystem struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_NVMe_NVMeSubsystem) Reset()         { *m = FrontEnd_NVMe_NVMeSubsystem{} }
func (m *FrontEnd_NVMe_NVMeSubsystem) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_NVMe_NVMeSubsystem) ProtoMessage()    {}
func (*FrontEnd_NVMe_NVMeSubsystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 0, 0}
}

func (m *FrontEnd_NVMe_NVMeSubsystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem.Unmarshal(m, b)
}
func (m *FrontEnd_NVMe_NVMeSubsystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem.Marshal(b, m, deterministic)
}
func (m *FrontEnd_NVMe_NVMeSubsystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem.Merge(m, src)
}
func (m *FrontEnd_NVMe_NVMeSubsystem) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem.Size(m)
}
func (m *FrontEnd_NVMe_NVMeSubsystem) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_NVMe_NVMeSubsystem proto.InternalMessageInfo

func (m *FrontEnd_NVMe_NVMeSubsystem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_NVMe_NVMeSubsystem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_NVMe_NVMeSubsystem) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_NVMe_NVMeController struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_NVMe_NVMeController) Reset()         { *m = FrontEnd_NVMe_NVMeController{} }
func (m *FrontEnd_NVMe_NVMeController) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_NVMe_NVMeController) ProtoMessage()    {}
func (*FrontEnd_NVMe_NVMeController) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 0, 1}
}

func (m *FrontEnd_NVMe_NVMeController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeController.Unmarshal(m, b)
}
func (m *FrontEnd_NVMe_NVMeController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeController.Marshal(b, m, deterministic)
}
func (m *FrontEnd_NVMe_NVMeController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_NVMe_NVMeController.Merge(m, src)
}
func (m *FrontEnd_NVMe_NVMeController) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeController.Size(m)
}
func (m *FrontEnd_NVMe_NVMeController) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_NVMe_NVMeController.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_NVMe_NVMeController proto.InternalMessageInfo

func (m *FrontEnd_NVMe_NVMeController) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_NVMe_NVMeController) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_NVMe_NVMeController) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_NVMe_NVMeNamespace struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_NVMe_NVMeNamespace) Reset()         { *m = FrontEnd_NVMe_NVMeNamespace{} }
func (m *FrontEnd_NVMe_NVMeNamespace) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_NVMe_NVMeNamespace) ProtoMessage()    {}
func (*FrontEnd_NVMe_NVMeNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 0, 2}
}

func (m *FrontEnd_NVMe_NVMeNamespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace.Unmarshal(m, b)
}
func (m *FrontEnd_NVMe_NVMeNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace.Marshal(b, m, deterministic)
}
func (m *FrontEnd_NVMe_NVMeNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace.Merge(m, src)
}
func (m *FrontEnd_NVMe_NVMeNamespace) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace.Size(m)
}
func (m *FrontEnd_NVMe_NVMeNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_NVMe_NVMeNamespace proto.InternalMessageInfo

func (m *FrontEnd_NVMe_NVMeNamespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_NVMe_NVMeNamespace) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_NVMe_NVMeNamespace) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_VirtioScsi struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_VirtioScsi) Reset()         { *m = FrontEnd_VirtioScsi{} }
func (m *FrontEnd_VirtioScsi) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_VirtioScsi) ProtoMessage()    {}
func (*FrontEnd_VirtioScsi) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 1}
}

func (m *FrontEnd_VirtioScsi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_VirtioScsi.Unmarshal(m, b)
}
func (m *FrontEnd_VirtioScsi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_VirtioScsi.Marshal(b, m, deterministic)
}
func (m *FrontEnd_VirtioScsi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_VirtioScsi.Merge(m, src)
}
func (m *FrontEnd_VirtioScsi) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_VirtioScsi.Size(m)
}
func (m *FrontEnd_VirtioScsi) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_VirtioScsi.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_VirtioScsi proto.InternalMessageInfo

func (m *FrontEnd_VirtioScsi) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_VirtioScsi) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_VirtioScsi) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_VirtioFS struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_VirtioFS) Reset()         { *m = FrontEnd_VirtioFS{} }
func (m *FrontEnd_VirtioFS) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_VirtioFS) ProtoMessage()    {}
func (*FrontEnd_VirtioFS) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 2}
}

func (m *FrontEnd_VirtioFS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_VirtioFS.Unmarshal(m, b)
}
func (m *FrontEnd_VirtioFS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_VirtioFS.Marshal(b, m, deterministic)
}
func (m *FrontEnd_VirtioFS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_VirtioFS.Merge(m, src)
}
func (m *FrontEnd_VirtioFS) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_VirtioFS.Size(m)
}
func (m *FrontEnd_VirtioFS) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_VirtioFS.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_VirtioFS proto.InternalMessageInfo

func (m *FrontEnd_VirtioFS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_VirtioFS) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_VirtioFS) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_VirtioBlk struct {
	Name                 string                                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ctrl                 []*FrontEnd_VirtioBlk_VirtioBlkCtrl   `protobuf:"bytes,3,rep,name=ctrl,proto3" json:"ctrl,omitempty"`
	Volume               []*FrontEnd_VirtioBlk_VirtioBlkVolume `protobuf:"bytes,4,rep,name=volume,proto3" json:"volume,omitempty"`
	LastUpdated          *timestamp.Timestamp                  `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *FrontEnd_VirtioBlk) Reset()         { *m = FrontEnd_VirtioBlk{} }
func (m *FrontEnd_VirtioBlk) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_VirtioBlk) ProtoMessage()    {}
func (*FrontEnd_VirtioBlk) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 3}
}

func (m *FrontEnd_VirtioBlk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_VirtioBlk.Unmarshal(m, b)
}
func (m *FrontEnd_VirtioBlk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_VirtioBlk.Marshal(b, m, deterministic)
}
func (m *FrontEnd_VirtioBlk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_VirtioBlk.Merge(m, src)
}
func (m *FrontEnd_VirtioBlk) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_VirtioBlk.Size(m)
}
func (m *FrontEnd_VirtioBlk) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_VirtioBlk.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_VirtioBlk proto.InternalMessageInfo

func (m *FrontEnd_VirtioBlk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_VirtioBlk) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_VirtioBlk) GetCtrl() []*FrontEnd_VirtioBlk_VirtioBlkCtrl {
	if m != nil {
		return m.Ctrl
	}
	return nil
}

func (m *FrontEnd_VirtioBlk) GetVolume() []*FrontEnd_VirtioBlk_VirtioBlkVolume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *FrontEnd_VirtioBlk) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_VirtioBlk_VirtioBlkCtrl struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) Reset()         { *m = FrontEnd_VirtioBlk_VirtioBlkCtrl{} }
func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_VirtioBlk_VirtioBlkCtrl) ProtoMessage()    {}
func (*FrontEnd_VirtioBlk_VirtioBlkCtrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 3, 0}
}

func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl.Unmarshal(m, b)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl.Marshal(b, m, deterministic)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl.Merge(m, src)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl.Size(m)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkCtrl proto.InternalMessageInfo

func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_VirtioBlk_VirtioBlkCtrl) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type FrontEnd_VirtioBlk_VirtioBlkVolume struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) Reset()         { *m = FrontEnd_VirtioBlk_VirtioBlkVolume{} }
func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) String() string { return proto.CompactTextString(m) }
func (*FrontEnd_VirtioBlk_VirtioBlkVolume) ProtoMessage()    {}
func (*FrontEnd_VirtioBlk_VirtioBlkVolume) Descriptor() ([]byte, []int) {
	return fileDescriptor_4026d13725e3c4b0, []int{0, 3, 1}
}

func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume.Unmarshal(m, b)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume.Marshal(b, m, deterministic)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume.Merge(m, src)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) XXX_Size() int {
	return xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume.Size(m)
}
func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd_VirtioBlk_VirtioBlkVolume proto.InternalMessageInfo

func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FrontEnd_VirtioBlk_VirtioBlkVolume) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*FrontEnd)(nil), "opiapistorage.FrontEnd")
	proto.RegisterType((*FrontEnd_NVMe)(nil), "opiapistorage.FrontEnd.NVMe")
	proto.RegisterType((*FrontEnd_NVMe_NVMeSubsystem)(nil), "opiapistorage.FrontEnd.NVMe.NVMeSubsystem")
	proto.RegisterType((*FrontEnd_NVMe_NVMeController)(nil), "opiapistorage.FrontEnd.NVMe.NVMeController")
	proto.RegisterType((*FrontEnd_NVMe_NVMeNamespace)(nil), "opiapistorage.FrontEnd.NVMe.NVMeNamespace")
	proto.RegisterType((*FrontEnd_VirtioScsi)(nil), "opiapistorage.FrontEnd.VirtioScsi")
	proto.RegisterType((*FrontEnd_VirtioFS)(nil), "opiapistorage.FrontEnd.VirtioFS")
	proto.RegisterType((*FrontEnd_VirtioBlk)(nil), "opiapistorage.FrontEnd.VirtioBlk")
	proto.RegisterType((*FrontEnd_VirtioBlk_VirtioBlkCtrl)(nil), "opiapistorage.FrontEnd.VirtioBlk.VirtioBlkCtrl")
	proto.RegisterType((*FrontEnd_VirtioBlk_VirtioBlkVolume)(nil), "opiapistorage.FrontEnd.VirtioBlk.VirtioBlkVolume")
}

func init() {
	proto.RegisterFile("api/storage/storage.proto", fileDescriptor_4026d13725e3c4b0)
}

var fileDescriptor_4026d13725e3c4b0 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0x9a, 0xac, 0xb4, 0x2f, 0x6c, 0x13, 0x3e, 0x85, 0x08, 0x89, 0xb0, 0x53, 0x4e, 0x0e,
	0x8c, 0x2b, 0x08, 0xa9, 0x15, 0x93, 0x38, 0xb0, 0x83, 0x0b, 0x3d, 0x70, 0x41, 0x4e, 0xe2, 0x55,
	0xd6, 0xec, 0x38, 0xb2, 0x9d, 0x4a, 0x7c, 0x02, 0x3e, 0x12, 0x5f, 0x89, 0x8f, 0x81, 0xe2, 0x24,
	0x2b, 0x1d, 0x62, 0x6b, 0x2f, 0x39, 0xe5, 0x25, 0xf9, 0xfd, 0x79, 0xfe, 0xf9, 0x3d, 0x78, 0x4e,
	0x6b, 0x9e, 0x19, 0xab, 0x34, 0xdd, 0xb0, 0xe1, 0x89, 0x6b, 0xad, 0xac, 0x42, 0xa7, 0xaa, 0xe6,
	0xb4, 0xe6, 0xfd, 0xc7, 0xf8, 0xe5, 0x46, 0xa9, 0x8d, 0x60, 0x99, 0xfb, 0x99, 0x37, 0x37, 0x99,
	0xe5, 0x92, 0x19, 0x4b, 0x65, 0xdd, 0xe1, 0x2f, 0x7e, 0x85, 0x30, 0xbb, 0xd2, 0xaa, 0xb2, 0x1f,
	0xab, 0x12, 0x21, 0x08, 0x2a, 0x2a, 0x59, 0xe4, 0x25, 0x5e, 0x3a, 0x27, 0xae, 0x46, 0x67, 0x30,
	0xe1, 0x65, 0x34, 0x49, 0xbc, 0xd4, 0x27, 0x13, 0x5e, 0xa2, 0xd7, 0x10, 0x54, 0x5b, 0xc9, 0x22,
	0x3f, 0xf1, 0xd3, 0xf0, 0xf2, 0x05, 0xde, 0xf3, 0xc3, 0x83, 0x14, 0xbe, 0x5e, 0x7f, 0x66, 0xc4,
	0x21, 0xd1, 0x02, 0x60, 0xcb, 0xb5, 0xe5, 0xca, 0x14, 0x86, 0x47, 0x81, 0xe3, 0x5d, 0xfc, 0x8f,
	0xb7, 0x76, 0xc8, 0x55, 0x61, 0x38, 0xf9, 0x8b, 0x85, 0xde, 0xc1, 0xac, 0x7b, 0xbb, 0x31, 0xd1,
	0x89, 0x53, 0x48, 0x1e, 0x56, 0xb8, 0x5a, 0x91, 0x3b, 0x06, 0xfa, 0x00, 0xf3, 0xae, 0xce, 0xc5,
	0x6d, 0x34, 0x75, 0xf4, 0x57, 0x0f, 0xd3, 0x17, 0xe2, 0x96, 0xec, 0x38, 0xe8, 0x3d, 0x3c, 0x15,
	0xd4, 0xd8, 0xef, 0x4d, 0x5d, 0x52, 0xcb, 0xca, 0xe8, 0x49, 0xe2, 0xa5, 0xe1, 0x65, 0x8c, 0xbb,
	0x74, 0xf1, 0x90, 0x2e, 0xfe, 0x32, 0xa4, 0x4b, 0xc2, 0x16, 0xff, 0xb5, 0x83, 0xc7, 0x3f, 0x7d,
	0x08, 0xda, 0x40, 0x0e, 0x09, 0x38, 0xd6, 0x70, 0xda, 0x62, 0x57, 0x4d, 0x6e, 0x7e, 0x18, 0xcb,
	0xe4, 0x41, 0xb7, 0x72, 0xbf, 0x41, 0xff, 0xb8, 0x06, 0x0d, 0x9c, 0xb5, 0x9e, 0x4b, 0x55, 0x59,
	0xad, 0x84, 0x60, 0x7a, 0x0c, 0xd3, 0xfe, 0xa0, 0xd7, 0x54, 0x32, 0x53, 0xd3, 0x82, 0x8d, 0xe1,
	0xa9, 0x00, 0x76, 0x13, 0x36, 0x86, 0xa1, 0x84, 0xd9, 0x30, 0x90, 0x63, 0xd8, 0xfd, 0xf6, 0x61,
	0x7e, 0x37, 0xc1, 0x07, 0x19, 0x2e, 0x21, 0x28, 0xac, 0x16, 0xfd, 0x3e, 0x67, 0x8f, 0xae, 0xc5,
	0xae, 0x5a, 0x5a, 0x2d, 0x88, 0x23, 0xa3, 0x4f, 0x30, 0xdd, 0x2a, 0xd1, 0x48, 0xd6, 0xaf, 0xf7,
	0x9b, 0x23, 0x64, 0xd6, 0x8e, 0x48, 0x7a, 0x81, 0x7f, 0x02, 0x38, 0x39, 0x7a, 0xa8, 0xf6, 0x1a,
	0x1c, 0x23, 0x74, 0x0b, 0xe7, 0xf7, 0x4e, 0x33, 0x82, 0xeb, 0xe2, 0xd9, 0xb7, 0x73, 0x9c, 0xed,
	0xc5, 0x9c, 0x4f, 0x1d, 0xe7, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xdd, 0xbd, 0xda,
	0x20, 0x06, 0x00, 0x00,
}
