name: opi-lab-regression
on: workflow_dispatch
jobs:
  opi-tgen:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v1
        - name: pytest-run0
          run: id
        - name: pytest-run1
          run: ls
        - name: pytest-run2
          run: pwd
        - name: pytest-run3
          run: pip install -r ./demos/tgen/requirements.txt
        - name: pytest-run4
          run: pytest -s ./tgen/test_tgen_demo.py
          working-directory: ./demos
          env:
            PYTHONPATH: ${PYTHONPATH}:${{ github.workspace }}/demos

  opi-ipsec:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v1
        - name: Install python requirements 
          run: pip install -r ./demos/security/nvidia/requirements.txt
        - name: Run CyPerf ipsec test automation
          run: pytest -s ./demos/security/nvidia/test_ipsec.py

  opi-ansible:
    runs-on: self-hosted
    steps:
        - name: nvidia bf-2 fw update using ansible
          run: |
              docker run --rm --pull=always \
                  ghcr.io/opiproject/ansible-opi-dpu:main \
                  all \
                  --module-name include_role \
                  --args name=bmc_fw_update \
                  -vvv -i "172.22.4.2," \
                  -e dpu_bmc_username='root' \
                  -e dpu_bmc_password='NvidiaBf2#Pass' \
                  -e bmc_fw_update_inventory_name='38a78c0e_bmc_firmware' \
                  -e bmc_fw_update_image_file='/tmp/bf2-bmc-ota-24.04-5-opn.tar'
