---
name: 'OPI Integration CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: integration shellcheck
      run: |
        make -C integration shellcheck

  run_integration_poc:
    needs: integration-shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build & Start containers
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml down
        docker network prune --force
        docker-compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml up -d
      working-directory: integration

    - name: Run Integration Tests
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml ps
        curl --fail http://127.0.0.1:8001/redfish/v1/Systems/437XR1138R2
        curl --fail http://127.0.0.1:8002/redfish/v1/Systems/437XR1138R2
        docker-compose -f docker-compose.pxe.yml exec -T pxe dnf install -y nmap tftp
        docker-compose -f docker-compose.pxe.yml exec -T pxe nmap --script broadcast-dhcp-discover | grep "Server Identifier: 10.127.127.3"
        docker-compose -f docker-compose.pxe.yml exec -T pxe curl --fail http://10.127.127.3:8082/var/lib/tftpboot/
        docker-compose -f docker-compose.pxe.yml exec -T pxe tftp 10.127.127.3 -v -c get grubx64.efi
      working-directory: integration

    - name: Logs
      if: failure()
      run: |
        docker-compose ps || true
        docker-compose logs || true
        netstat -an || true
        ifconfig -a || true
        docker inspect `docker-compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml ps -aq` || true
      working-directory: integration

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.yml -f docker-compose.telegraf.yml -f docker-compose.pxe.yml down
      working-directory: integration
