---
name: 'OPI Integration CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: integration shellcheck
      run: |
        make -C integration shellcheck

  run_integration_poc:
    needs: integration-shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build containers
      run: ./scripts/integration.sh build
      working-directory: integration

    - name: Start containers
      run: ./scripts/integration.sh start
      working-directory: integration

    - name: Run Integration Tests
      run: ./scripts/integration.sh tests
      working-directory: integration

    - name: Logs
      if: failure()
      run: ./scripts/integration.sh logs
      working-directory: integration

    - name: Stop containers
      if: always()
      run: ./scripts/integration.sh stop
      working-directory: integration
