---
name: 'OPI Security PoC CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'security/**'
      - '.github/workflows/poc-security.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'security/**'
      - '.github/workflows/poc-security.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository_owner }}/opi-spdk

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Start containers
      run: docker-compose up -d
      working-directory: security

    - name: Run Tests
      run: docker-compose ps
      working-directory: security

    - name: Logs
      if: failure()
      run: docker-compose logs
      working-directory: security

    - name: Stop containers
      if: always()
      run: docker-compose down
      working-directory: security
