---
name: 'OPI Storage PoC CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-storage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storage-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - server
          - client
          - spdk
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/opi-storage-${{ matrix.package }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        context: storage/${{ matrix.package }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  docker-build:
    runs-on: ubuntu-latest
    steps:

    - name: configure HUGE pages
      run: |
        sync
        echo 1 | sudo tee /proc/sys/vm/drop_caches
        sudo mkdir -p /mnt/huge
        grep hugetlbfs /proc/mounts || sudo mount -t hugetlbfs nodev /mnt/huge
        echo 1024 | sudo tee /proc/sys/vm/nr_hugepages
        echo "Check and fail if not enough"
        grep 1024 /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Start containers
      run: SPDK_TAG=sha-$(git rev-parse --short ${{ github.sha }}) ./scripts/poc.sh start
      working-directory: storage

    - name: Run Tests
      run: SPDK_TAG=sha-$(git rev-parse --short ${{ github.sha }}) ./scripts/poc.sh tests
      working-directory: storage

    - name: Logs
      if: failure()
      run: ./scripts/poc.sh logs
      working-directory: storage

    - name: Stop containers
      if: always()
      run: ./scripts/poc.sh stop
      working-directory: storage
